### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by nithins1** [nithins1/task-manager#6]
- [x] single page app (f6d1777dae330d6f5422b9e4350efa239c6a70ff)
- [x] tagging feature (#5)
- [x] assigning tasks to multiple other users (#8)
- [x] [optional] colors for tags (#7)
- [ ] [optional] progress tracker for tasks (percentage done?)
- [ ] comments
- [x] documentation (#11)
- [x] deadline timezone bug (#10)
